matrix:
  include:
    - language: python
      python: 2.7
      before_install:
        - cd server
      install: pip install -r requirements.txt
      before_script:
        - cd server
      script:
        - python manage.py test

    - language: node_js
      node_js: 7
      before_install:
        - cd client
        - npm install -g bower
        - npm install -g grunt-cli
      install:
        - npm install
        - bower install --allow-root
      before_script:
        - cd client
      script:
        - grunt

notifications:
  email:
    - harripobre@gmail.com
